version: 2

jobs:
  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh kindest/node:v1.21.1

  deploy:
    docker:
      - image: web3f/ci-commons:v2.4.14
    steps:
      - checkout
      - run:
          environment:
            HELM_ENV: production
            CLUSTER: community
          command: |
            /scripts/deploy.sh -c community


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - integrationTests:
          filters:
            tags:
              only: /.*/

      - deploy:
          context: digital_ocean_access
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests
