environments:
  #production:
  ci:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: ghost-staging
  chart: bitnami/ghost
  namespace: ghost
  version: 15.2.0
  values:
  - ./config/ghost-values.yaml.gotmpl
