environments:
  production:
  ci:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: ghost-staging
  chart: bitnami/ghost
  version: 15.0.1
  values:
  - ./config/ghost-values.yaml.gotmpl
